/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/bin/bash: /afs/ifh.de/user/t/tuccia/.profile: Permission denied
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/lustre/fs24/group/cqta/atucci/environment2/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
